version: "3.9"

services:



  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      #- DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=SupersetDB
    restart: unless-stopped
    volumes:
      - db_home:/var/lib/postgresql/data
    container_name: superset_db
    
  redis:
    image: redis:latest
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - "127.0.0.1:6379:6379"
      
  superset:
    env_file: .env-non-dev
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - db
      - redis
    container_name: superset

volumes:
  db_home:
    external: false
  redis:
    external: false

