version: "3.9"

services:

  superset:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - db
    container_name: superset

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      #- DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=SupersetDB
    restart: unless-stopped
    volumes:
      - db_home:/var/lib/postgresql/data
    container_name: superset_db

volumes:
  db_home:
    external: false
